# POLF 3D - Copyright (c) 2026 oNdsen. Licensed under the MIT License, see LICENSE.

<#
.SYNOPSIS
    Authoring tool: generates the campaign maps (maps/level1.map ... level5.map) from room lists.
.DESCRIPTION
    Typing grids of two-character cells by hand is error prone, so every floor is described as
    rooms (rectangles carved out of solid rock), doors and things. Rooms that touch or overlap
    merge into one space - that is how corridors and caves are made. The result is a plain text
    map; the game only ever reads the .map files, so they may be edited by hand afterwards.
    Run tools/Test-Level.ps1 to validate the result.

    The floors get harder: more and tougher enemies, fewer gifts, bigger bosses.
#>
[CmdletBinding()]
param([string]$OutDir = (Join-Path $PSScriptRoot '../maps'))

$script:grid = $null; $script:W = 0; $script:H = 0

function New-Grid([int]$Width, [int]$Height) {
    $script:W = $Width; $script:H = $Height
    $script:grid = New-Object 'string[,]' $Width, $Height          # $null = untouched rock
}

function Set-Cell([int]$X, [int]$Y, [string]$Code) {
    if ($X -lt 1 -or $Y -lt 1 -or $X -ge $script:W - 1 -or $Y -ge $script:H - 1) { throw "Cell $X,$Y ('$Code') is on or beyond the map border" }
    $isWallCode = $Code -cmatch '^([SBWRMGT][A-Za-z]|\?.|D[DGSL0-9]|X[0-9])$'
    if (-not $isWallCode -and $script:grid[$X, $Y] -ne '..') { throw "Cell $X,$Y is not free ('$($script:grid[$X, $Y])') for '$Code'" }
    $script:grid[$X, $Y] = $Code
}

# Carves the interior and gives untouched rock around it this room's wall texture (first room wins).
# $Things: flat list dx, dy, code, ... RELATIVE to the room's top left floor tile.
function Add-Room([int]$X, [int]$Y, [int]$Width, [int]$Height, [string]$Wall, [object[]]$Things = @()) {
    for ($yy = $Y - 1; $yy -le $Y + $Height; $yy++) {
        for ($xx = $X - 1; $xx -le $X + $Width; $xx++) {
            if ($xx -lt 0 -or $yy -lt 0 -or $xx -ge $script:W -or $yy -ge $script:H) { throw "Room at $X,$Y reaches beyond the map" }
            $inside = $xx -ge $X -and $xx -lt $X + $Width -and $yy -ge $Y -and $yy -lt $Y + $Height
            if ($inside) { if ($script:grid[$xx, $yy] -notmatch '^\S\S$' -or $script:grid[$xx, $yy] -cmatch '^[SBWRMGT]') { $script:grid[$xx, $yy] = '..' } }
            elseif ($null -eq $script:grid[$xx, $yy]) { $script:grid[$xx, $yy] = $Wall }
        }
    }
    for ($i = 0; $i -lt $Things.Count; $i += 3) { Set-Cell ($X + $Things[$i]) ($Y + $Things[$i + 1]) $Things[$i + 2] }
}

function Add-Things([object[]]$List) {           # flat list with ABSOLUTE coordinates: x, y, code, ...
    for ($i = 0; $i -lt $List.Count; $i += 3) { Set-Cell $List[$i] $List[$i + 1] $List[$i + 2] }
}

function Save-Level([int]$Number, [string]$Name, [int]$Par, [string]$Ceiling, [string]$Floor, [string]$Rock) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("; POLF 3D - floor $Number. Generated by tools/New-Levels.ps1, may be edited by hand.")
    $lines.Add('; Every cell is TWO characters wide. Legend: see the header of src/Map.ps1 or the README.')
    $lines.Add('; Copyright (c) 2026 oNdsen. Licensed under the MIT License, see LICENSE.')
    $lines.Add("@name $Name"); $lines.Add("@par $Par"); $lines.Add("@ceiling $Ceiling"); $lines.Add("@floor $Floor"); $lines.Add('@map')
    for ($y = 0; $y -lt $script:H; $y++) {
        $sb = [System.Text.StringBuilder]::new()
        for ($x = 0; $x -lt $script:W; $x++) { $null = $sb.Append($(if ($null -eq $script:grid[$x, $y]) { $Rock } else { $script:grid[$x, $y] })) }
        $lines.Add($sb.ToString())
    }
    $null = New-Item -ItemType Directory -Path $OutDir -Force
    $file = Join-Path $OutDir "level$Number.map"
    [System.IO.File]::WriteAllLines($file, $lines)
    Write-Host ("floor {0}: {1,-22} {2}x{3}  -> {4}" -f $Number, $Name, $script:W, $script:H, $file)
}

# =====================================================================================================
# FLOOR 1 - Shellstein Dungeon.  Gentle start: guards and dogs, the first elites and mutants, all four
# secrets are generous. Ends with the commander (gold key) and an elite squad in front of the lift.
# =====================================================================================================
New-Grid 58 37
Add-Room 19 13 12 13 'SS'      # hub hall
Add-Room  6 24  3 12 'BB'      # cell corridor
Add-Room  2 32  3  4 'BB'      # start cell
Add-Room  2 26  3  4 'BB'      # second cell
Add-Room  4 16  8  7 'SS'      # guard room
Add-Room 13 18  5  3 'SS'      # passage guard room -> hub
Add-Room 23 27  3  3 'RR'      # passage hub -> kennels
Add-Room 14 30 13  6 'RR'      # kennels
Add-Room 15  5 11  7 'WW'      # officers' wing
Add-Room 32 14 12 11 'RR'      # storage
Add-Room 33 26 11 10 'MM'      # laboratory
Add-Room 45 15  8  9 'SS'      # commander's hall
Add-Room 27  2 14 10 'SS'      # last stand before the lift
Add-Room 42  6  3  3 'MM'      # lift
Add-Room 10 31  3  5 'RR'      # secret: kennels
Add-Room 18  1  5  3 'WW'      # secret: officers' wing
Add-Room 29 29  3  3 'MM'      # secret: laboratory
Add-Room 54 18  3  3 'SS'      # secret: commander's hall
Add-Things @(
    5, 33, 'DD',   5, 28, 'DD',   7, 23, 'DD',   12, 19, 'DD',   18, 19, 'DD'
    24, 26, 'DD',  21, 12, 'DD',  31, 19, 'DS',  38, 25, 'DD',   44, 19, 'DD'
    28, 12, 'DG',  41, 7, 'DL',   45, 7, 'MX'
    13, 33, '?r',  20, 4, '?w',   32, 30, '?M',  53, 19, '?s'
    9, 26, 'Bc',   9, 30, 'Bc',   9, 34, 'Bc',   5, 25, 'Bc',    5, 30, 'Bc'
    6, 15, 'Sb',   9, 15, 'Sb',   23, 12, 'Sb',  26, 12, 'Sb',   21, 26, 'Sb',  27, 26, 'Sb'
    18, 16, 'Sp',  18, 22, 'Sp',  31, 1, 'Sb',   36, 1, 'Sb',    53, 16, 'Sb',  53, 22, 'Sb'
    14, 8, 'Wp',   26, 7, 'Ws',   17, 4, 'Ws',   23, 4, 'Wp'
    31, 16, 'Rb',  44, 16, 'Rb',  13, 31, 'Rb'
    # start cell, cells, corridor
    3, 35, 'P^',   3, 32, '*k',   2, 33, '*s',   4, 34, '*u'
    2, 26, '+a',   3, 27, '+f',   4, 29, '*s'
    7, 27, 'g^',   7, 25, '*l',   7, 31, '*l',   8, 35, '+d'
    # guard room + passage
    5, 18, 'g>',   7, 21, 'gE',   5, 21, ':>',   10, 21, ':<'
    8, 18, '*t',   9, 18, '+f',   4, 16, '+a',   7, 19, '*l',    11, 16, '*L'
    16, 19, 'g<',  14, 19, '*l'
    # hub
    22, 16, '*c',  27, 16, '*c',  22, 22, '*c',  27, 22, '*c',   24, 19, '*h'
    24, 14, 'gE',  20, 14, ':>',  29, 14, ':v',  29, 24, ':<',   20, 24, ':^'
    26, 24, 'dW',  25, 17, 'gv',  30, 19, 'e<'
    19, 13, '+1',  30, 25, '+a',  19, 25, '+h',  30, 13, '*f'
    # kennels + secret
    16, 31, 'dE',  22, 31, 'dW',  15, 31, ':>',  25, 31, ':<'
    18, 34, 'dE',  24, 34, 'dW',  15, 34, ':>',  25, 34, ':<'
    20, 33, 'g^',  18, 32, '*b',  19, 32, '*b',  24, 28, '*l'
    14, 30, '+d',  26, 35, '+d',  14, 35, '+d',  26, 30, '+a'
    10, 31, '+m',  10, 35, '+2',  12, 35, '+a',  12, 31, '+1'
    # officers' wing + secret
    20, 6, 'ov',   16, 9, 'o>',   24, 10, 'g<'
    18, 8, '*t',   22, 8, '*t',   15, 5, '*p',   25, 5, '*p',    15, 11, '*a',  25, 11, '*a',  20, 8, '*h'
    16, 6, '+s',   24, 6, '+1',   25, 8, '+2',   17, 5, '+3',    19, 8, '+f'
    18, 1, '+p',   22, 1, '+4',   18, 3, '+u',   22, 3, '+a'
    # storage
    34, 16, '*x',  35, 16, '*x',  34, 17, '*x',  38, 20, '*x',   39, 20, '*x',  38, 21, '*x',  41, 15, '*x',  36, 23, '*x'
    42, 23, '*b',  43, 23, '*b',  36, 17, '*e',  40, 21, '*e',  37, 23, '*e'
    40, 18, 'e<',  33, 16, 'eS',  33, 23, ':^',  33, 14, ':v',   42, 19, 'g<',  43, 14, 'gw'
    32, 24, '+a',  41, 24, '+a',  37, 14, '+h',  43, 16, '+f'
    # laboratory + secret
    35, 28, '*v',  35, 32, '*v',  41, 28, '*v',  41, 32, '*v',   38, 31, '*l'
    38, 30, 'm^',  43, 27, 'mw',  33, 34, 'me',  42, 34, 'm<'
    33, 26, '+h',  43, 35, '+a',  38, 35, '+3'
    29, 29, '+c',  31, 29, '+a',  29, 31, '+h',  31, 31, '+a'
    # commander's hall + secret
    50, 19, 'b<',  47, 17, '*c',  47, 21, '*c',  52, 15, '*f',   52, 23, '*f',  49, 19, '*h'
    45, 15, '+h',  45, 23, '+h',  46, 15, '+a',  46, 23, '+a',   46, 19, '+q'
    54, 18, '+r',  56, 18, '+z',  54, 20, '+z',  56, 20, '+z'
    # last stand + lift
    34, 4, 'ev',   29, 3, 'ev',   39, 3, 'ev',   32, 6, 'ov',    36, 6, 'ov'
    30, 5, '*c',   37, 5, '*c',   30, 9, '*c',   37, 9, '*c'
    27, 2, '+h',   40, 2, '+h',   27, 11, '+a',  40, 11, '+a',   34, 2, '+2',   33, 11, '+a',  35, 11, '+h'
    43, 7, '*l'
)
Save-Level 1 'Shellstein Dungeon' 330 '383838' '6E6E6E' 'SS'

# =====================================================================================================
# FLOOR 2 - The Barracks.  One long corridor with patrols, dorms and a mess hall full of guards. The
# silver key lies in the office behind the mess hall; a commander holds the lift lobby.
# =====================================================================================================
New-Grid 50 36
Add-Room 3 18 40 4 'SS' @(                                   # main corridor
    5, 1, 'gE',   1, 1, ':>',   38, 1, ':<',   30, 2, 'gW',   1, 2, ':>',   38, 2, ':<'
    22, 0, 'o<',  12, 3, 'e>',  34, 0, 'h<',  6, 0, '*l',    16, 3, '*l',   26, 0, '*l',  36, 3, '*l',   0, 0, '*f',  0, 3, '*f')
Add-Room 3 23 5 5 'MM' @(2, 3, 'P^',  2, 1, '*l',  0, 0, '+a')                      # arrival
Add-Room 3 9 9 8 'WW' @(                                     # dorm A - some of them are asleep
    0, 0, '*B',  0, 2, '*B',  0, 4, '*B',  8, 0, '*B',  8, 2, '*B',  8, 4, '*B',  4, 3, '*t'
    2, 1, 'gn',  6, 3, 'gw',  3, 5, 'g>',  6, 6, 'gs',  4, 0, '+f',  8, 7, '+a',  0, 7, '+1',  8, 6, '+j')
Add-Room 13 9 9 8 'WW' @(                                    # dorm B
    0, 0, '*B',  0, 2, '*B',  0, 4, '*B',  8, 0, '*B',  8, 2, '*B',  8, 4, '*B'
    4, 2, 'ov',  6, 5, 'g<',  2, 6, 'gs',  8, 7, '+h',  0, 7, '+2')
Add-Room 23 6 12 11 'SS' @(                                  # mess hall
    2, 3, '*t',  6, 3, '*t',  2, 7, '*t',  6, 7, '*t',  4, 5, '*h',  9, 5, '*h'
    3, 2, 'gv',  7, 8, 'g^',  9, 4, 'g<',  1, 5, 'g>',  10, 1, 'e<',  10, 9, 'e<'
    3, 3, '+f',  7, 7, '+f',  0, 10, '+a')
Add-Room 25 2 8 3 'SS' @(1, 1, 'g>',  0, 0, '+f',  7, 0, '+f',  7, 2, '+d',  3, 0, '*b',  4, 0, '*b')       # kitchen
Add-Room 36 9 6 8 'WW' @(                                    # the office: silver key
    3, 3, 'o<',  4, 5, 'o<',  2, 1, 'e<',  4, 1, '*t',  5, 0, '+s',  5, 7, '+3',  0, 0, '*p',  0, 7, '*p',  5, 4, '*a')
Add-Room 10 23 8 7 'RR' @(                                   # armoury
    2, 3, 'e^',  6, 4, 'e^',  0, 0, '*x',  1, 0, '*x',  7, 0, '*x',  0, 6, '*x'
    2, 6, '+a',  6, 6, '+a',  7, 3, '+a',  3, 1, '+m',  0, 3, '+h',  5, 1, '*e',  6, 1, '*e')
Add-Room 20 23 9 8 'RR' @(                                   # kennels
    2, 2, 'dE',  1, 2, ':>',  7, 2, ':<',  6, 5, 'dW',  1, 5, ':>',  7, 5, ':<',  3, 5, 'dE',  4, 7, 'd^',  4, 3, 'g^'
    0, 0, '+d',  8, 0, '+d',  0, 7, '+d',  8, 7, '+d')
Add-Room 31 23 8 6 'BB' @(1, 1, '*u',  5, 3, '*u',  2, 4, '*u',  6, 1, 'g<',  1, 4, 'gn',  7, 5, '+h',  0, 0, '+a')   # wash room
Add-Room 44 15 5 8 'MM' @(3, 3, 'b<',  1, 1, 'e<',  3, 6, 'e<',  0, 7, '+a',  4, 7, '+h',  2, 4, '*l')             # lift lobby
Add-Room 45 11 3 3 'MM' @(1, 1, '*l')                                                                              # lift
Add-Room 15 5 5 3 'WW' @(0, 0, '+c',  4, 0, '+a',  0, 2, '+3',  4, 2, '+a')                                       # secret: dorm B
Add-Room 12 31 5 3 'RR' @(0, 0, '+u',  4, 0, '+4',  0, 2, '+a',  4, 2, '+q')                                       # secret: armoury
Add-Things @(
    5, 22, 'DD',   7, 17, 'DD',   17, 17, 'DD',  28, 17, 'DD',  29, 5, 'DD',   35, 12, 'DD'
    14, 22, 'D1',  42, 14, 'X1',  24, 22, 'DD',  35, 22, 'DD',  43, 19, 'DS',  46, 14, 'DL',  46, 10, 'MX'
    17, 8, '?w',   14, 30, '?r'
    12, 17, 'Sb',  22, 17, 'Sb',  32, 17, 'Sp',  38, 17, 'Sp',  9, 22, 'Sb',   19, 22, 'Sb',  30, 22, 'Sb',  40, 22, 'Sb'
    42, 12, 'Wp',  38, 8, 'Ws',   2, 12, 'Wp',   22, 12, 'Ws'
)
Save-Level 2 'The Barracks' 300 '403830' '6A6258' 'SS'

# =====================================================================================================
# FLOOR 3 - The Catacombs.  Caves and crypts: dogs in the dark, mutants lying in ambush behind every
# pillar. Silver key in the officers' crypt, gold key in the vault, a commander guards the lift.
# =====================================================================================================
New-Grid 50 43
Add-Room 2 38 5 4 'GG' @(2, 2, 'P^',  0, 0, '*s',  4, 3, '+a',  4, 0, '+j')                       # arrival cave
Add-Room 4 30 2 8 'GG'
Add-Room 2 24 8 6 'GG' @(                                    # dog cave
    1, 1, 'dE',  0, 1, ':>',  7, 1, ':<',  6, 4, 'd<',  3, 4, 'd^',  4, 3, '*g',  7, 5, '*s',  0, 5, '+d',  7, 0, '+f')
Add-Room 10 26 8 2 'GG' @(6, 0, 'mW',  7, 0, ':<')
Add-Room 18 22 9 9 'GG' @(                                   # pillar crypt: ambush!
    2, 2, '*c',  6, 2, '*c',  2, 6, '*c',  6, 6, '*c',  0, 0, 'me',  8, 0, 'mw',  1, 8, 'me',  8, 8, 'mw',  4, 1, 'ms'
    4, 4, '+h',  1, 7, '*s',  7, 1, '*s')
Add-Room 21 14 2 8 'GG'
Add-Room 16 6 12 8 'SS' @(                                   # officers' crypt: silver key
    3, 2, 'ov',  8, 2, 'ov',  1, 5, 'g>',  10, 5, 'g<',  5, 3, '*t',  1, 0, '+s',  0, 0, '*a',  11, 0, '*a'
    10, 0, '+2', 6, 3, '+f',  4, 6, 'e^',  6, 5, 'hv')
Add-Room 27 25 8 2 'GG'
Add-Room 35 20 10 12 'GG' @(                                 # flooded hall
    2, 2, '*u',  6, 4, '*u',  3, 8, '*u',  7, 9, '*u',  5, 2, '*g',  2, 9, '*g',  8, 7, '*g'
    7, 5, 'e<',  8, 6, 'e<',  4, 1, 'ev',  5, 10, 'e^',  9, 2, 'g<',  9, 9, 'g<',  0, 0, '+a',  9, 11, '+h',  0, 11, '+a',  3, 4, 'mw',  3, 7, 'mw',  9, 5, 's<')
Add-Room 36 10 9 9 'BB' @(                                   # the vault: gold key
    4, 0, '+g',  2, 2, 'mv',  6, 2, 'mv',  4, 3, 'ov',  0, 0, '+3',  8, 0, '+3',  0, 8, '+2',  8, 8, '+4',  2, 5, '*c',  6, 5, '*c')
Add-Room 34 33 12 8 'SS' @(                                  # the commander's crypt
    6, 5, 'b^',  2, 4, 'm^',  10, 4, 'm^',  4, 6, 'e^',  8, 6, 'e^',  3, 2, '*c',  8, 2, '*c',  0, 7, '+h',  11, 7, '+h',  0, 0, '+a',  11, 0, '+a')
Add-Room 30 36 3 3 'MM' @(1, 1, '*l')                                                                              # lift
Add-Room 7 39 12 2 'GG'
Add-Room 19 34 8 8 'GG' @(6, 1, 'k<',  2, 6, 'k<',  5, 2, 'd<',  6, 5, 'd<',  3, 3, 'g<',  7, 0, '+a',  7, 7, '+a',  0, 0, '+f',  4, 1, '*g',  0, 7, '+t')
Add-Room 22 31 2 3 'GG'
Add-Room 20 2 5 3 'SS' @(0, 0, '+p',  4, 0, '+u',  0, 2, '+a',  4, 2, '+a')                                       # secret: crypt
Add-Room 12 29 5 3 'GG' @(0, 0, '+c',  4, 0, '+a',  0, 2, '+h',  4, 2, '+1')                                       # secret: tunnel
Add-Room 46 13 3 3 'BB' @(0, 0, '+r',  2, 0, '+z',  0, 2, '+z',  2, 2, '+q')                                       # secret: vault
Add-Things @(
    3, 26, ':>',   11, 26, '~s',  11, 27, '~s'
    40, 19, 'DS',  40, 32, 'DG',  33, 37, 'DL',  29, 37, 'MX'
    22, 5, '?s',   14, 28, '?g',  45, 14, '?B'
    15, 9, 'Sb',   28, 9, 'Sb',   10, 25, 'Gv',  1, 27, 'Gv',   17, 24, 'Gv',  27, 28, 'Gv',  34, 22, 'Gv',  45, 28, 'Gv'
    6, 37, 'Gv',   18, 38, 'Gv',  27, 36, 'Gv',  35, 14, 'Bc',  45, 11, 'Bc',  33, 35, 'Sb',  46, 36, 'Sb'
)
Save-Level 3 'The Catacombs' 420 '1E2A1C' '4A5240' 'GG'

# =====================================================================================================
# FLOOR 4 - Lab Zero.  A ring corridor with elite patrols around the reactor hall. The silver key is
# in lab B, the commander sits on the gold key in the server room, and behind the gold door waits
# the first war machine.
# =====================================================================================================
New-Grid 52 45
Add-Room 8 6 36 3 'TT'; Add-Room 8 6 3 27 'TT'; Add-Room 41 6 3 27 'TT'; Add-Room 8 30 36 3 'TT'      # the ring
Add-Room 25 9 3 3 'TT'; Add-Room 25 26 3 4 'TT'; Add-Room 11 18 4 3 'TT'; Add-Room 37 18 4 3 'TT'    # spokes
Add-Room 16 13 20 12 'TT' @(                                 # reactor hall
    8, 4, '*v',  11, 4, '*v',  8, 7, '*v',  11, 7, '*v',  3, 2, '*m',  16, 2, '*m',  3, 9, '*m',  16, 9, '*m'
    6, 2, 'ev',  13, 2, 'ev',  6, 9, 'e^',  13, 9, 'e^',  0, 0, 'me',  19, 0, 'mw',  0, 11, 'me',  19, 11, 'mw',  15, 5, 'o<'
    9, 5, '+h',  10, 6, '+a',  9, 9, 'h^',  10, 2, 'hv')
Add-Room 2 28 5 5 'MM' @(2, 2, 'P>',  2, 1, '*l',  0, 0, '+a',  0, 4, '+h')                                          # arrival
Add-Room 12 1 10 4 'TT' @(1, 0, '*v',  8, 0, '*v',  4, 0, '*m',  3, 1, 'mv',  6, 1, 'mv',  9, 3, 'ms',  9, 0, '+h',  0, 3, '+a')     # lab A
Add-Room 30 1 12 4 'TT' @(0, 0, '*v',  3, 0, '*v',  8, 0, '*v',  11, 0, '*v',  11, 3, '+s',  5, 1, 'ov',  2, 2, 'mv',  9, 2, 'mv',  10, 1, 'e<',  0, 3, '+f')   # lab B
Add-Room 45 10 6 10 'RR' @(                                  # storage
    1, 0, '*x',  2, 0, '*x',  5, 3, '*x',  2, 5, '*x',  3, 5, '*x',  0, 8, '*x',  5, 9, '*x'
    3, 3, 'e<',  4, 7, 'g<',  5, 0, 'gw',  0, 0, '+a',  1, 9, '+a',  4, 9, '+a',  5, 5, '+m',  0, 5, '+h',  4, 4, '*e',  1, 6, '*e',  3, 9, '+l')
Add-Room 45 22 6 9 'TT' @(                                   # server room: commander + gold key
    1, 0, '*m',  3, 0, '*m',  5, 0, '*m',  1, 8, '*m',  3, 8, '*m',  3, 4, 'b<',  4, 2, 'e<',  4, 6, 'e<',  0, 8, '+h',  0, 0, '+a')
Add-Room 14 34 12 5 'BB' @(                                  # holding cells
    5, 2, 'k^',  7, 3, 'k^',  1, 1, '*s',  9, 3, '*s',  4, 2, '*u',  2, 3, 'm^',  8, 2, 'm^',  11, 4, 'mn',  11, 0, '+f',  6, 4, '+h',  3, 0, '+a')
Add-Room 28 34 13 9 'MM' @(                                  # hangar of the war machine
    6, 6, 'u^',  3, 3, '*c',  9, 3, '*c',  3, 6, '*c',  9, 6, '*c',  1, 7, 'e^',  11, 7, 'e^'
    0, 0, '+h',  12, 0, '+h',  0, 8, '+a',  12, 8, '+a',  6, 8, '+z',  6, 2, '*e',  1, 4, '*e',  11, 4, '*e',  5, 0, '+o',  7, 0, '+o')
Add-Room 42 35 3 3 'MM' @(1, 1, '*l')                                                                               # lift
Add-Room 8 1 3 3 'TT' @(0, 0, '+p',  2, 0, '+a',  0, 2, '+a',  2, 2, '+2')                                          # secret: lab A
Add-Room 46 6 5 3 'RR' @(0, 0, '+z',  4, 0, '+z',  0, 2, '+q',  4, 2, '+r')                                         # secret: storage
Add-Room 10 35 3 3 'BB' @(0, 0, '+c',  2, 0, '+a',  0, 2, '+a',  2, 2, '+3')                                        # secret: cells
Add-Things @(
    # three patrols walk the ring clockwise
    8, 6, 's>',    43, 32, 's<',  25, 27, '~s',  26, 27, '~s',  27, 27, '~s',  38, 18, '~c',  38, 19, '~c',  38, 20, '~c',
    12, 7, 'eE',   30, 31, 'eW',  42, 15, 'mS',  42, 7, ':v',  42, 31, ':<',  9, 31, ':^',  9, 7, ':>'
    7, 30, 'DD',   16, 5, 'DD',   35, 5, 'DD',   44, 14, 'DD',  44, 26, 'DS',  19, 33, 'DD',  34, 33, 'DG'
    26, 12, 'DD',  26, 25, 'DD',  15, 19, 'DD',  36, 19, 'DD',  41, 36, 'DL',  45, 36, 'MX'
    11, 2, '?T',   48, 9, '?R',   13, 36, '?B'
    20, 5, 'Tl',   28, 5, 'Tl',   40, 5, 'Tl',   7, 12, 'Tl',   7, 20, 'Tl',   12, 33, 'Tl',  28, 33, 'Tl',  40, 33, 'Tl'
    20, 12, 'Tl',  32, 12, 'Tl',  20, 25, 'Tl',  32, 25, 'Tl',  15, 15, 'Tl',  15, 23, 'Tl',  36, 15, 'Tl',  36, 23, 'Tl'
    16, 39, 'Bc',  22, 39, 'Bc',  44, 20, 'Tl',  44, 10, 'Tl'
)
Save-Level 4 'Lab Zero' 480 '20262E' '4A525C' 'TT'

# =====================================================================================================
# FLOOR 5 - The Citadel.  The finale: a gate hall, the great hall with three patrols, mutants in the
# west tower (silver key), TWO commanders in the east tower (gold key) and, in the throne hall, the
# war machine with its escort.
# =====================================================================================================
New-Grid 48 46
Add-Room 12 16 24 15 'SS' @(                                 # great hall
    4, 3, '*c',  9, 3, '*c',  14, 3, '*c',  19, 3, '*c',  4, 11, '*c',  9, 11, '*c',  14, 11, '*c',  19, 11, '*c'
    11, 7, '*h',  6, 7, '*h',  17, 7, '*h'
    3, 1, 'eE',  18, 13, 'eW',  22, 6, 'oS',  22, 1, ':v',  22, 13, ':<',  1, 13, ':^',  1, 1, ':>'
    2, 3, 's>',  21, 3, 's<',  8, 5, 'ov',  15, 5, 'ov',  6, 9, 'mv',  17, 9, 'mv',  3, 7, 'g>',  20, 7, 'g<',  11, 3, 'ev'
    0, 0, '+h',  23, 0, '+h',  0, 14, '+a',  23, 14, '+a',  11, 8, '+3')
Add-Room 21 40 6 4 'MM' @(2, 2, 'P^',  0, 0, '+h',  5, 0, '+a')                                                     # arrival
Add-Room 17 32 14 7 'SS' @(                                  # gate hall
    5, 2, 'hv',  8, 2, 'hv',  3, 1, 'gv',  10, 1, 'gv',  7, 1, 'ev',  2, 5, 'dE',  0, 5, ':>',  13, 5, ':<',  11, 3, 'dW',  0, 3, ':>',  13, 3, ':<'
    0, 0, '*f',  13, 0, '*f',  0, 6, '+a',  13, 6, '+a')
Add-Room 3 18 8 10 'BB' @(                                   # west tower: silver key
    0, 0, '+s',  1, 2, 'm>',  1, 7, 'm>',  4, 4, 'me',  3, 9, 'm>',  5, 1, 'm>',  6, 1, '*s',  2, 5, '*s',  5, 8, '*u'
    0, 9, '+h',  7, 0, '+c',  7, 9, '+t')
Add-Room 37 18 8 10 'RR' @(                                  # east tower: two commanders, one gold key each
    5, 2, 'b<',  5, 7, 'b<',  2, 4, 'e<',  7, 0, '*x',  7, 9, '*x',  0, 0, '*x',  0, 9, '+a',  7, 5, '+h',  7, 4, '+z',  3, 1, '*e',  3, 8, '*e')
Add-Room 14 3 20 12 'MM' @(                                  # throne hall
    7, 4, 'kv',  12, 4, 'kv',  10, 1, 'uv',  3, 3, 'ev',  16, 3, 'ev',  0, 0, 'ms',  19, 0, 'ms',  6, 2, 'ov',  13, 2, 'ov'
    4, 5, '*c',  15, 5, '*c',  4, 9, '*c',  15, 9, '*c',  9, 7, '*c',  10, 7, '*c'
    0, 11, '+h',  19, 11, '+h',  1, 11, '+a',  18, 11, '+a',  8, 11, '+z',  10, 11, '+q',  2, 11, '+o',  17, 11, '+o',  8, 9, '~s',  9, 9, '~s',  10, 9, '~s',  11, 9, '~s')
Add-Room 35 7 3 3 'MM' @(1, 1, '*l')                                                                                # lift
Add-Room 8 29 3 3 'SS' @(0, 0, '+z',  2, 0, '+z',  0, 2, '+u',  2, 2, '+a')                                         # secret: west
Add-Room 37 29 3 3 'SS' @(0, 0, '+q',  2, 0, '+4',  0, 2, '+a',  2, 2, '+h')                                        # secret: east
Add-Room 10 7 3 3 'MM' @(0, 0, '+r',  2, 0, '+z',  0, 2, '+z',  2, 2, '+p')                                         # secret: throne hall
Add-Things @(
    23, 39, 'DD',  23, 31, 'DD',  11, 23, 'D2',  31, 34, 'X2',  36, 23, 'DS',  23, 15, 'DG',  34, 8, 'DL',  38, 8, 'MX'
    11, 30, '?s',  36, 30, '?s',  13, 8, '?M'
    14, 15, 'Sb',  18, 15, 'Sb',  28, 15, 'Sb',  32, 15, 'Sb',  14, 31, 'Sb',  32, 31, 'Sb',  11, 19, 'Sp',  36, 19, 'Sp'
    2, 20, 'Bc',   2, 25, 'Bc',   45, 22, 'Rb',  16, 39, 'Sb',  31, 35, 'Sb'
)
Save-Level 5 'The Citadel' 540 '30203A' '5A5060' 'SS'
